import subprocess

def bat_all():
    # subprocess.run('python start.py -t BAS_COMP_CAPSTRUCTURE -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t BAS_COMP_INFORMATION -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t BAS_IDX_INFORMATION -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t BAS_STK_HISDISTRIBUTION -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t BAS_STK_INFORMATION -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_CICC -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_CITIC -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_GICS -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_IDX -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_ROLL_CICC -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_ROLL_CITIC -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_ROLL_GICS -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_ROLL_IDX -st 20070101 -md overwrite --fu 3', shell = True)
    # subprocess.run('python start.py -t CON_FORECAST_ROLL_STK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_FORECAST_ROLL_SW -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_FORECAST_STK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_FORECAST_SW -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_RATING_STK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_TARGET_PRICE_STK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t DER_NEW_FORTUNE_AUTHOR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_BANK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_GEN -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_INSUR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_SEC -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_SINGLE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_BALANCE_SHEET_TTM -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_BANK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_GEN -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_INSUR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_SEC -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_SINGLE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_CASH_FLOW_TTM -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_BANK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_GEN -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_INSUR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_SEC -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_SINGLE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_INCOME_TTM -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_MAIN_INDICATOR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_MAIN_RATIO -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_PERFORMANCE_EXPRESS  -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_PERFORMANCE_FORECAST  -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_IDX_ CONSTITUENTS -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_IDX_DAILY -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_INDUS_CATEGORIES -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_INDUS_CONSTITUENTS  -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_NTRADE_DATE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_STK_BLOCK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_STK_DAILY -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_SW_DAILY -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_SW_INDUS_HIS -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t QT_TRADE_DATE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_AUTHOR_INFORMATION  -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_EARNINGS_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_FORECAST_STK -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_GOGOAL_RATING -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_ORGAN_INFORMATION  -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_RATING_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_RATING_COMPARE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_REPORT_AUTHOR -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_REPORT_CAPITAL -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_REPORT_EVENT -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_REPORT_RELIABILITY -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_REPORT_TYPE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_TARGET_PRICE_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)

def bat_partial():
    subprocess.run('python start.py -t RPT_FORECAST_STK -st 20070101 -md overwrite --fu 3', shell=True)

def test_append():
    subprocess.run('python start.py -t CON_FORECAST_STK -st 20070101 -md append --fu 5', shell=True)  # 测试通过
    subprocess.run('python start.py -t RPT_FORECAST_STK -st 20070101 -md append --fu 5', shell=True)   # 测试通过
    subprocess.run('python start.py -t CON_FORECAST_ROLL_STK -st 20070101 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_RATING_COMPARE -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_EARNINGS_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_TARGET_PRICE_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t RPT_RATING_ADJUST -st 20070101 -md overwrite --fu 3', shell = True)
    subprocess.run('python start.py -t CON_RATING_STK -st 20070101 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t CON_TARGET_PRICE_STK -st 20070101 -md append --fu 3', shell = True)

def test_append2():
    subprocess.run('python start.py -t DER_FORECAST_RANK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_EXCESS_STOCK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_PROB_EXCESS_STOCK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_CONF_STK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_FOCUS_STK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_DIVER_STK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_CON_DEV_STK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_CON_DEV_ROLL_STK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t BAS_STK_HISDISTRIBUTION -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_FORECAST_ADJUST_NUM -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_RATING_STRENGTH_RANK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_FORECAST_ROLL_RANK -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t DER_RATING_ADJUST_NUM -st 20220501 -md append --fu 3', shell = True)
    subprocess.run('python start.py -t FIN_PERFORMANCE_FORECAST -st 20220501 -md append --fu 3', shell = True)

if __name__ == '__main__':
    test_append()
    test_append2()
